AWSTemplateFormatVersion: 2010-09-09
Description: >
  Task 8 - Automated VM Backups and Lifecycle Rules
  Project: slackbot, Student: srabonty

Parameters:
  ProjectName:
    Type: String
    Default: slackbot
  StudentName:
    Type: String
    Default: srabonty
  BackupPlanSchedule:
    Type: String
    Default: cron(0 5 * * ? *)   # Daily at 05:00 UTC
    Description: CRON expression for backup frequency

Resources:

  # ----------------------------------------------------
  # Backup Vault
  # ----------------------------------------------------
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Sub "${ProjectName}-${StudentName}-vault"
      Tags:
        Project: !Ref ProjectName
        Student: !Ref StudentName
        Task: "Task8"

  # ----------------------------------------------------
  # IAM Role for AWS Backup Service
  # ----------------------------------------------------
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${StudentName}-backup-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: backup.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForRestores
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Student
          Value: !Ref StudentName

  # ----------------------------------------------------
  # Backup Plan (Daily backup + lifecycle rules)
  # ----------------------------------------------------
  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Sub "${ProjectName}-${StudentName}-backup-plan"
        Rules:
          - RuleName: DailyBackupRule
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: !Ref BackupPlanSchedule
            Lifecycle:
              DeleteAfterDays: 30   # Lifecycle: delete after 30 days
              MoveToColdStorageAfterDays: 7
            RecoveryPointTags:
              Student: !Ref StudentName
              Project: !Ref ProjectName
              Task: "Task8"

  # ----------------------------------------------------
  # Backup Selection: Select EC2 instances by TAG
  # ----------------------------------------------------
  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlan
      BackupSelection:
        SelectionName: !Sub "${ProjectName}-${StudentName}-selection"
        IamRoleArn: !GetAtt BackupRole.Arn
        Resources:
          - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
        ListOfTags:
          - ConditionType: STRINGEQUALS
            ConditionKey: Backup
            ConditionValue: "true"

Outputs:
  BackupVaultName:
    Value: !Ref BackupVault
    Description: Backup vault created

  BackupPlanID:
    Value: !Ref BackupPlan
    Description: Backup plan created

  IAMRoleArn:
    Value: !GetAtt BackupRole.Arn
    Description: IAM Role used by AWS Backup
