AWSTemplateFormatVersion: '2010-09-09'
Description: "Task 1 - Networking for Slack Chatbot (Project: slackbot, Student: srabonty)"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: slackbot-t1-vpc-srabonty
        - Key: Course
          Value: CloudTraining
        - Key: Implementation
          Value: IaC
        - Key: Task
          Value: Task1
        - Key: Student
          Value: srabonty
        - Key: DeploymentType
          Value: Sandbox
         
  # Public Subnet AZ1
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: slackbot-t1-public-az1-srabonty

  # Public Subnet AZ2
  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: slackbot-t1-public-az2-srabonty

  # Private Subnet AZ1
  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: slackbot-t1-private-az1-srabonty

  # Private Subnet AZ2
  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: slackbot-t1-private-az2-srabonty

