AWSTemplateFormatVersion: 2010-09-09
Description: Task 4 - S3 Storage (Student: srabonty)

Parameters:
  ProjectName:
    Type: String
    Default: slackbot
  StudentName:
    Type: String
    Default: srabonty
  Environment:
    Type: String
    Default: sandbox

Resources:
  # Public bucket
  PublicBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-public-${StudentName}-${AWS::AccountId}"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-${StudentName}"
        - Key: Course
          Value: CloudTraining
        - Key: Implementation
          Value: IaC
        - Key: Task
          Value: Task4
        - Key: Student
          Value: !Ref StudentName
        - Key: DeploymentType
          Value: !Ref Environment

  # Public bucket policy
  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${PublicBucket.Arn}/*"

  # Private bucket
  ProtectedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-protected-${StudentName}-${AWS::AccountId}"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-protected-${StudentName}"
        - Key: Course
          Value: CloudTraining
        - Key: Implementation
          Value: IaC
        - Key: Task
          Value: Task4
        - Key: Student
          Value: !Ref StudentName
        - Key: DeploymentType
          Value: !Ref Environment

Outputs:
  PublicBucketName:
    Description: Public S3 bucket name
    Value: !Ref PublicBucket

  ProtectedBucketName:
    Description: Protected S3 bucket name
    Value: !Ref ProtectedBucket

       
