AWSTemplateFormatVersion: 2010-09-09
Description: >
  Task 3 - VM Deployment for Slack Chatbot (Project: slackbot, Student: srabonty)
  Creates EC2 with Key Pair and networking from previous tasks.

Parameters:
  ProjectName:
    Type: String
    Default: slackbot
  StudentName:
    Type: String
    Default: srabonty
  Environment:
    Type: String
    Default: sandbox
  KeyPairName:
    Type: String
    Default: slackbot-key-srabonty
    Description: Key pair name for SSH access

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc-${StudentName}"
        - Key: Course
          Value: CloudTraining
        - Key: Implementation
          Value: IaC
        - Key: Task
          Value: Task3
        - Key: Student
          Value: !Ref StudentName
        - Key: DeploymentType
          Value: !Ref Environment

  # Subnets
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-az1-${StudentName}"

  # Internet Gateway + Route Table
  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable

  # Firewall Groups
  PublicSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public access SG
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-sg-${StudentName}"

  # Key Pair
  EC2KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyPairName
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-key-${StudentName}"

  # EC2 VM
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c2b8ca1dad447f8a # Amazon Linux 2 (will work in AWS Academy)
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SubnetId: !Ref PublicSubnetAZ1
      SecurityGroupIds:
        - !Ref PublicSG
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vm-${StudentName}"
        - Key: Course
          Value: CloudTraining
        - Key: Implementation
          Value: IaC
        - Key: Task
          Value: Task3
        - Key: Student
          Value: !Ref StudentName
        - Key: DeploymentType
          Value: !Ref Environment

Outputs:
  VMPublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Public IP of the EC2 instance
